name: init
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # Internationalization
  easy_localization: ^3.0.7

  # Go router, for routing
  go_router: ^14.7.2

  # Sidebar
  sidebarx: ^0.17.1

  # Google fonts
  google_fonts: ^6.2.1

  #Dependency injection
  get_it: ^8.0.1
  injectable: ^2.5.0

  # Shared preferences
  shared_preferences: ^2.3.2

  # Theme
  flex_color_scheme: ^7.3.1

  # Chart
  fl_chart: ^0.70.2

  # Copy with extension
  copy_with_extension: ^5.0.4

  # Equatable
  equatable: ^2.0.5

  # Material color utilities
  material_color_utilities: ^0.11.1

  # Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  
  # Secure storage
  flutter_secure_storage: ^9.2.2

  # Calendar date picker
  calendar_date_picker2: ^1.1.8

  # Uuid
  uuid: ^4.5.1

  # Collection
  collection: ^1.19.0

  # Json serializable
  json_annotation: ^4.9.0

  # Gap
  gap: ^3.0.1
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  cloud_functions: ^5.3.2

  # Svg
  flutter_svg: ^2.0.17

  # Intl
  intl: ^0.19.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Lints
  flutter_lints: ^4.0.0
  
  # Riverpod
  riverpod_generator: ^2.6.2
  
  # Build runner
  build_runner: ^2.4.13

  # Custom lint for Riverpod
  custom_lint: ^0.7.0

  # Riverpod lint
  riverpod_lint: ^2.6.2

  # Auto route
  auto_route_generator: ^9.0.0

  # Copy with extension
  copy_with_extension_gen: ^5.0.0

  # Injectable, for dependency injection
  injectable_generator: ^2.6.2
  
  # Json serializable
  json_serializable: ^6.7.1

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  assets:
    - assets/translations/
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: InitIcons
      fonts:
        - asset: assets/icons/InitIcons.ttf

